# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170504_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='player.Room'),
        ),
    ]
